"""Generate an interactive HTML dashboard from insurance pipeline CSV outputs.

Reads the same CSVs produced by ``src/transform.py`` and ``src/model.py`` and
assembles a self-contained, single-file HTML dashboard with interactive Plotly
charts.  The Plotly JS bundle is embedded inline from the installed package so
no web server or internet connection is required to view the file.

Charts included
---------------
* **KPIs** — paid totals and claim counts by member region, split by network status.
* **Monthly Trends** — paid totals over time, grouped by member region.
* **Loss Ratio** — billed / allowed / paid amounts side-by-side with loss ratio %.
* **Network Utilization** — pie chart of in-network vs out-of-network claims.
* **Diagnosis Summary** — top-10 ICD codes ranked by paid total.
* **Model Metrics** — accuracy card from the predictive model run.

Usage
-----
    python -m src.generate_html_report \\
        --output-dir outputs/client_a \\
        --client-name "Client A" \\
        --out outputs/client_a/dashboard.html
"""

from __future__ import annotations

import argparse
import html as html_mod
import os
import pathlib
from datetime import UTC, datetime

import pandas as pd

# Use PEP 604 union types (X | Y) instead of typing.Optional


try:
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots

    _PLOTLY_AVAILABLE = True
except ImportError:  # pragma: no cover
    _PLOTLY_AVAILABLE = False


# ── Colour palette ─────────────────────────────────────────────────────────────
_BLUE = "#1565C0"
_LIGHT_BLUE = "#42A5F5"
_ORANGE = "#EF6C00"
_GREEN = "#2E7D32"
_RED = "#C62828"
_GREY = "#757575"


def _normalize_network(value: object) -> str:
    """Return ``'In-Network'`` or ``'Out-of-Network'`` for any in_network encoding."""
    s = str(value).strip().lower()
    if s in ("true", "1", "yes"):
        return "In-Network"
    return "Out-of-Network"


def _network_color(label: str) -> str:
    return _BLUE if label == "In-Network" else _ORANGE


# ── HTML page template ─────────────────────────────────────────────────────────
_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{client_name} — Insurance Analytics Dashboard</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #F5F7FA;
      color: #212121;
    }}
    header {{
      background: {brand_color};
      color: #fff;
      padding: 18px 28px 14px;
      display: flex;
      align-items: baseline;
      gap: 16px;
    }}
    header h1 {{ font-size: 1.4rem; font-weight: 600; }}
    header small {{ font-size: 0.78rem; opacity: 0.8; }}
    .tabs {{
      display: flex;
      flex-wrap: wrap;
      gap: 4px;
      padding: 14px 20px 0;
      background: #fff;
      border-bottom: 2px solid #E3E8F0;
    }}
    .tab-btn {{
      padding: 8px 18px;
      border: none;
      background: transparent;
      cursor: pointer;
      font-size: 0.88rem;
      font-weight: 500;
      color: #555;
      border-bottom: 3px solid transparent;
      margin-bottom: -2px;
      transition: color 0.15s, border-color 0.15s;
    }}
    .tab-btn:hover {{ color: {brand_color}; }}
    .tab-btn.active {{
      color: {brand_color};
      border-bottom-color: {brand_color};
    }}
    .tab-pane {{ display: none; padding: 20px; }}
    .tab-pane.active {{ display: block; }}
    .card {{
      background: #fff;
      border-radius: 8px;
      padding: 20px;
      box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    }}
    .metric-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 16px;
      margin-bottom: 20px;
    }}
    .metric-card {{
      background: #fff;
      border-radius: 8px;
      padding: 16px 20px;
      box-shadow: 0 1px 4px rgba(0,0,0,0.08);
      border-left: 4px solid {brand_color};
    }}
    .metric-card .label {{ font-size: 0.78rem; color: #888; text-transform: uppercase; letter-spacing: 0.04em; }}
    .metric-card .value {{ font-size: 1.5rem; font-weight: 700; color: #212121; margin-top: 4px; }}
    .metric-card .sub {{ font-size: 0.78rem; color: #666; margin-top: 2px; }}
    .no-data {{
      display: flex;
      align-items: center;
      justify-content: center;
      height: 200px;
      color: #aaa;
      font-size: 1rem;
      font-style: italic;
    }}
    footer {{
      text-align: center;
      padding: 20px;
      font-size: 0.75rem;
      color: #aaa;
    }}
  </style>
  {plotly_js}
</head>
<body>
  <header>
    <h1>📊 {client_name} — Insurance Analytics Dashboard</h1>
    <small>Generated {timestamp} UTC</small>
  </header>

  <div class="tabs">
    {tab_buttons}
  </div>

  {tab_panes}

  <footer>
    Generated by the Insurance Analytics Pipeline ·
    <a href="https://github.com/sahithisarvepalli/insurance-analytics-project" style="color:{brand_color}">
      insurance-analytics-project
    </a>
  </footer>

  <script>
    function showTab(id) {{
      document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));
      document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
      document.getElementById('pane-' + id).classList.add('active');
      document.querySelector('[data-tab="' + id + '"]').classList.add('active');
    }}
    // Activate the first tab on load
    document.addEventListener('DOMContentLoaded', function() {{
      var first = document.querySelector('.tab-btn');
      if (first) showTab(first.getAttribute('data-tab'));
    }});
  </script>
</body>
</html>
"""


# ── Helper: read CSV safely ────────────────────────────────────────────────────


def _read_csv(filename: str, output_dir: str) -> pd.DataFrame | None:
    """Return a DataFrame for *filename* inside *output_dir*, or None if absent."""
    path = os.path.join(output_dir, filename)
    return pd.read_csv(path) if os.path.exists(path) else None


def _fig_div(fig: go.Figure) -> str:
    """Convert a Plotly figure to an HTML div without the surrounding page markup."""
    return fig.to_html(
        full_html=False,
        include_plotlyjs=False,
        config={"displayModeBar": True, "responsive": True},
    )


# ── Chart builders ─────────────────────────────────────────────────────────────


def _kpis_content(df: pd.DataFrame | None) -> str:
    """Return HTML content for the KPIs tab."""
    if df is None or df.empty:
        return '<div class="no-data">No KPI data available.</div>'

    paid_total = df["paid_total"].sum()
    total_claims = df["claims"].sum()
    paid_avg = paid_total / total_claims if total_claims > 0 else 0.0

    metric_html = f"""
    <div class="metric-grid">
      <div class="metric-card">
        <div class="label">Total Paid</div>
        <div class="value">${paid_total:,.0f}</div>
        <div class="sub">across all regions &amp; age bands</div>
      </div>
      <div class="metric-card">
        <div class="label">Total Claims</div>
        <div class="value">{total_claims:,}</div>
        <div class="sub">all network statuses</div>
      </div>
      <div class="metric-card">
        <div class="label">Avg Paid per Claim</div>
        <div class="value">${paid_avg:,.2f}</div>
        <div class="sub">Total paid / total claims</div>
      </div>
    </div>
    """

    region_df = df.groupby("member_region")[["claims", "paid_total"]].sum().reset_index()

    # Cap to top 10 regions by paid total so charts stay readable for datasets
    # with many distinct region values (e.g. individual hospital names).
    _MAX_REGIONS = 10
    top_regions = region_df.nlargest(_MAX_REGIONS, "paid_total")["member_region"].tolist()
    region_df = region_df[region_df["member_region"].isin(top_regions)]

    # Normalise in_network to a canonical label so colours are consistent
    # regardless of whether the column holds bool, int, or string values.
    df = df.copy()
    df = df[df["member_region"].isin(top_regions)]
    df["_nw_label"] = df["in_network"].map(_normalize_network)
    network_labels = sorted(df["_nw_label"].unique())

    fig = make_subplots(
        rows=1,
        cols=2,
        subplot_titles=("Paid Total by Region & Network", "Claims Count by Region"),
        horizontal_spacing=0.12,
    )

    for label in network_labels:
        sub = df[df["_nw_label"] == label]
        by_region = sub.groupby("member_region")["paid_total"].sum().reset_index()
        fig.add_trace(
            go.Bar(
                name=label,
                x=by_region["member_region"],
                y=by_region["paid_total"],
                marker_color=_network_color(label),
            ),
            row=1,
            col=1,
        )

    fig.add_trace(
        go.Bar(
            name="Claims",
            x=region_df["member_region"],
            y=region_df["claims"],
            marker_color=_LIGHT_BLUE,
            showlegend=False,
        ),
        row=1,
        col=2,
    )

    fig.update_layout(
        height=420,
        barmode="group",
        margin={"t": 50, "b": 40, "l": 60, "r": 20},
        paper_bgcolor="white",
        plot_bgcolor="#F8FAFD",
        legend={"orientation": "h", "y": -0.15},
    )
    fig.update_yaxes(tickprefix="$", row=1, col=1)

    return metric_html + '<div class="card">' + _fig_div(fig) + "</div>"


def _monthly_content(df: pd.DataFrame | None) -> str:
    """Return HTML content for the Monthly Trends tab."""
    if df is None or df.empty:
        return '<div class="no-data">No monthly trend data available.</div>'

    df = df.copy()
    df["month"] = pd.to_datetime(df["month"])

    # Aggregate across in_network so each region has one line per month,
    # avoiding duplicate x-values when the CSV is grouped by
    # [month, member_region, in_network].
    df = df.groupby(["month", "member_region"])[["paid_total", "claims"]].sum().reset_index()

    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Monthly Paid Total by Region", "Monthly Claim Count by Region"),
        vertical_spacing=0.12,
    )

    df["member_region"] = df["member_region"].astype(str)

    # Cap to top 10 regions by total paid to keep the chart fast regardless of
    # how many distinct regions (e.g. hospital names) are in the dataset.
    _MAX_REGIONS = 10
    top_regions = (
        df.groupby("member_region")["paid_total"].sum().nlargest(_MAX_REGIONS).index.tolist()
    )
    df = df[df["member_region"].isin(top_regions)]

    regions = sorted(df["member_region"].dropna().unique())
    palette = [_BLUE, _ORANGE, _GREEN, _RED, _GREY, _LIGHT_BLUE]
    for i, region in enumerate(regions):
        sub = df[df["member_region"] == region].sort_values("month")
        color = palette[i % len(palette)]
        fig.add_trace(
            go.Scatter(
                x=sub["month"],
                y=sub["paid_total"],
                name=region,
                mode="lines+markers",
                line={"color": color, "width": 2},
                marker={"size": 5},
            ),
            row=1,
            col=1,
        )
        fig.add_trace(
            go.Scatter(
                x=sub["month"],
                y=sub["claims"],
                name=region,
                mode="lines+markers",
                line={"color": color, "width": 2, "dash": "dot"},
                marker={"size": 5},
                showlegend=False,
            ),
            row=2,
            col=1,
        )

    fig.update_layout(
        height=520,
        margin={"t": 60, "b": 40, "l": 70, "r": 20},
        paper_bgcolor="white",
        plot_bgcolor="#F8FAFD",
        legend={"orientation": "h", "y": -0.12},
    )
    fig.update_yaxes(tickprefix="$", row=1, col=1)

    return '<div class="card">' + _fig_div(fig) + "</div>"


def _loss_ratio_content(df: pd.DataFrame | None) -> str:
    """Return HTML content for the Loss Ratio tab."""
    if df is None or df.empty:
        return '<div class="no-data">No loss ratio data available.</div>'

    df = df.copy()

    # Aggregate to region level (collapse in_network) and cap to top 10 by paid_total.
    # This keeps the chart readable even when there are thousands of distinct regions
    # (e.g. individual hospital names from a healthcare admissions dataset).
    _MAX_REGIONS = 10
    region_agg = (
        df.groupby("member_region", dropna=False)
        .agg(
            claims=("claims", "sum"),
            billed_total=("billed_total", "sum"),
            allowed_total=("allowed_total", "sum"),
            paid_total=("paid_total", "sum"),
        )
        .reset_index()
    )
    top_regions = region_agg.nlargest(_MAX_REGIONS, "paid_total")["member_region"].tolist()
    region_agg = region_agg[region_agg["member_region"].isin(top_regions)]

    # Recompute loss ratio on the aggregated totals (billed may be 0 for some datasets).
    billed_pos = region_agg["billed_total"] > 0
    region_agg["loss_ratio_pct"] = (
        (region_agg["paid_total"] / region_agg["billed_total"].where(billed_pos) * 100)
        .where(billed_pos)
        .round(2)
    )

    has_loss_ratio = region_agg["loss_ratio_pct"].notna().any()
    # Billed/allowed are non-zero only when the source dataset carries those fields.
    has_billed = (region_agg["billed_total"] > 0).any()
    has_allowed = (region_agg["allowed_total"] > 0).any()

    x_labels = region_agg["member_region"].astype(str)

    cols = 2 if has_loss_ratio else 1
    subplot_titles = (
        ("Billed / Allowed / Paid by Region (Top 10)", "Loss Ratio % by Region")
        if has_loss_ratio
        else ("Billed / Allowed / Paid by Region (Top 10)",)
    )
    fig = make_subplots(
        rows=1,
        cols=cols,
        subplot_titles=subplot_titles,
        horizontal_spacing=0.14,
    )

    # Always show Paid.  Add Billed and Allowed when the dataset carries them
    # so the chart renders the full "billed vs allowed vs paid" comparison.
    if has_billed:
        fig.add_trace(
            go.Bar(name="Billed", x=x_labels, y=region_agg["billed_total"], marker_color=_BLUE),
            row=1,
            col=1,
        )
    if has_allowed:
        fig.add_trace(
            go.Bar(
                name="Allowed", x=x_labels, y=region_agg["allowed_total"], marker_color=_LIGHT_BLUE
            ),
            row=1,
            col=1,
        )
    fig.add_trace(
        go.Bar(name="Paid", x=x_labels, y=region_agg["paid_total"], marker_color=_GREEN),
        row=1,
        col=1,
    )

    if has_loss_ratio:
        fig.add_trace(
            go.Bar(
                name="Loss Ratio %",
                x=x_labels,
                y=region_agg["loss_ratio_pct"],
                marker_color=_ORANGE,
                text=region_agg["loss_ratio_pct"].round(1).astype(str) + "%",
                textposition="outside",
            ),
            row=1,
            col=2,
        )

    fig.update_layout(
        height=440,
        barmode="group",
        margin={"t": 50, "b": 80, "l": 70, "r": 20},
        paper_bgcolor="white",
        plot_bgcolor="#F8FAFD",
        legend={"orientation": "h", "y": -0.25},
    )
    fig.update_yaxes(tickprefix="$", row=1, col=1)
    if has_loss_ratio:
        fig.update_yaxes(ticksuffix="%", range=[0, 110], row=1, col=2)
    fig.update_xaxes(tickangle=-30)

    return '<div class="card">' + _fig_div(fig) + "</div>"


def _network_content(df: pd.DataFrame | None) -> str:
    """Return HTML content for the Network Utilization tab."""
    if df is None or df.empty:
        return '<div class="no-data">No network utilization data available.</div>'

    labels = df["in_network"].map(_normalize_network)
    colors = [_network_color(lb) for lb in labels]

    fig = make_subplots(
        rows=1,
        cols=2,
        specs=[[{"type": "pie"}, {"type": "bar"}]],
        subplot_titles=("Claims Split", "Cost & Utilization by Network"),
    )

    fig.add_trace(
        go.Pie(
            labels=labels,
            values=df["claims"],
            marker_colors=colors,
            hole=0.4,
            textinfo="percent+label",
        ),
        row=1,
        col=1,
    )

    fig.add_trace(
        go.Bar(
            name="Paid Total",
            x=labels,
            y=df["paid_total"],
            marker_color=colors,
            text=df["utilization_pct"].round(1).astype(str) + "% util.",
            textposition="outside",
        ),
        row=1,
        col=2,
    )

    fig.update_layout(
        height=420,
        margin={"t": 50, "b": 40, "l": 60, "r": 20},
        paper_bgcolor="white",
        plot_bgcolor="#F8FAFD",
        showlegend=False,
    )
    fig.update_yaxes(tickprefix="$", row=1, col=2)

    return '<div class="card">' + _fig_div(fig) + "</div>"


def _diagnosis_content(df: pd.DataFrame | None) -> str:
    """Return HTML content for the Diagnosis Summary tab."""
    if df is None or df.empty:
        return '<div class="no-data">No diagnosis data available.</div>'

    top10 = df.nlargest(10, "paid_total").copy()
    top10["diagnosis_code"] = top10["diagnosis_code"].astype(str)

    fig = make_subplots(
        rows=1,
        cols=2,
        subplot_titles=("Top 10 Diagnosis Codes — Paid Total", "Claims Count"),
        horizontal_spacing=0.14,
    )

    fig.add_trace(
        go.Bar(
            x=top10["paid_total"],
            y=top10["diagnosis_code"],
            orientation="h",
            marker_color=_BLUE,
            name="Paid Total",
        ),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Bar(
            x=top10["claims"],
            y=top10["diagnosis_code"],
            orientation="h",
            marker_color=_LIGHT_BLUE,
            name="Claims",
        ),
        row=1,
        col=2,
    )

    fig.update_layout(
        height=420,
        margin={"t": 50, "b": 40, "l": 80, "r": 20},
        paper_bgcolor="white",
        plot_bgcolor="#F8FAFD",
        yaxis={"autorange": "reversed"},
        yaxis2={"autorange": "reversed"},
        showlegend=False,
    )
    fig.update_xaxes(tickprefix="$", row=1, col=1)

    return '<div class="card">' + _fig_div(fig) + "</div>"


def _model_content(metrics_text: str | None) -> str:
    """Return HTML content for the Model Metrics tab."""
    if not metrics_text:
        return '<div class="no-data">No model metrics available. Run src.model first.</div>'

    lines = metrics_text.strip().splitlines()
    rows_html = "".join(
        f'<tr><td style="padding:8px 16px;border-bottom:1px solid #eee;">'
        f"{html_mod.escape(line)}</td></tr>"
        for line in lines
    )

    return f"""
    <div class="card">
      <h3 style="margin-bottom:16px;color:#555;font-size:0.95rem;text-transform:uppercase;letter-spacing:0.05em;">
        Predictive Model — High-Cost Member Classification
      </h3>
      <table style="width:100%;border-collapse:collapse;font-family:monospace;font-size:0.9rem;">
        {rows_html}
      </table>
    </div>
    """


# ── Plotly JS embed helper ─────────────────────────────────────────────────────


def _get_plotly_js_tag() -> str:
    """Return a ``<script>`` tag containing the embedded Plotly JS bundle.

    Reads the bundle shipped with the installed ``plotly`` package so the
    resulting HTML is fully self-contained and works without any internet
    connection.

    Raises
    ------
    FileNotFoundError
        If the expected Plotly package data file cannot be located.  This
        typically means the installed version of plotly is too old or the
        package layout has changed.  Re-install with
        ``pip install 'plotly>=5.18.0,<6.0.0'``.
    """
    import plotly as _plotly  # noqa: PLC0415

    candidate = pathlib.Path(_plotly.__file__).parent / "package_data" / "plotly.min.js"
    if candidate.exists():
        js = candidate.read_text(encoding="utf-8")
        return f"<script>{js}</script>"
    raise FileNotFoundError(
        f"Plotly JS bundle not found at '{candidate}'.  "
        "Re-install plotly with: pip install 'plotly>=5.18.0,<6.0.0'"
    )


# ── Dashboard assembly ─────────────────────────────────────────────────────────

_TABS = [
    ("kpis", "📈 KPIs"),
    ("monthly", "📅 Monthly Trends"),
    ("loss_ratio", "💰 Loss Ratio"),
    ("network", "🌐 Network"),
    ("diagnosis", "🏥 Diagnosis"),
    ("model", "🤖 Model Metrics"),
]


def generate_dashboard(output_dir: str, client_name: str, brand_color: str = _BLUE) -> str:
    """Build a self-contained HTML dashboard string from pipeline CSV outputs.

    Parameters
    ----------
    output_dir:
        Directory containing the CSV files produced by ``src/transform.py``.
    client_name:
        Human-readable client name shown in the page header.
    brand_color:
        Hex colour used for the header and tab accents.

    Returns
    -------
    str
        Full HTML document as a string.
    """
    if not _PLOTLY_AVAILABLE:
        raise ImportError(
            "plotly is required to generate the HTML dashboard.  "
            "Install it with:  pip install 'plotly>=5.18.0,<6.0.0'"
        )

    kpis_df = _read_csv("kpis.csv", output_dir)
    monthly_df = _read_csv("monthly.csv", output_dir)
    loss_ratio_df = _read_csv("loss_ratio.csv", output_dir)
    network_df = _read_csv("network_summary.csv", output_dir)
    diagnosis_df = _read_csv("diagnosis_summary.csv", output_dir)

    metrics_text: str | None = None
    metrics_path = os.path.join(output_dir, "model_metrics.txt")
    if os.path.exists(metrics_path):
        with open(metrics_path, encoding="utf-8") as fh:
            metrics_text = fh.read()

    tab_content_map = {
        "kpis": _kpis_content(kpis_df),
        "monthly": _monthly_content(monthly_df),
        "loss_ratio": _loss_ratio_content(loss_ratio_df),
        "network": _network_content(network_df),
        "diagnosis": _diagnosis_content(diagnosis_df),
        "model": _model_content(metrics_text),
    }

    tab_buttons = "\n    ".join(
        f'<button class="tab-btn" data-tab="{tab_id}" onclick="showTab(\'{tab_id}\')">'
        f"{label}</button>"
        for tab_id, label in _TABS
    )

    tab_panes = "\n  ".join(
        f'<div id="pane-{tab_id}" class="tab-pane">{tab_content_map[tab_id]}</div>'
        for tab_id, _ in _TABS
    )

    timestamp = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M")
    plotly_js = _get_plotly_js_tag()

    return _HTML_TEMPLATE.format(
        client_name=html_mod.escape(client_name),
        brand_color=brand_color,
        timestamp=timestamp,
        plotly_js=plotly_js,
        tab_buttons=tab_buttons,
        tab_panes=tab_panes,
    )


# ── CLI entry-point ────────────────────────────────────────────────────────────


def main(out: str, output_dir: str = "outputs", client_name: str = "Insurance Analytics") -> None:
    """Generate an interactive HTML dashboard and write it to *out*.

    Parameters
    ----------
    out:
        Destination path for the HTML file.
    output_dir:
        Directory containing the pipeline CSV outputs to read.
    client_name:
        Client name shown in the page header.
    """
    html = generate_dashboard(output_dir=output_dir, client_name=client_name)
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(html)
    print(f"[{client_name}] HTML dashboard written → {out}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(
        description="Generate an interactive HTML dashboard from pipeline CSV outputs."
    )
    ap.add_argument(
        "--out",
        default=None,
        help="Output HTML file path (default: <output-dir>/dashboard.html).",
    )
    ap.add_argument(
        "--output-dir",
        default="outputs",
        help="Directory containing pipeline CSV outputs (default: outputs).",
    )
    ap.add_argument(
        "--client-name",
        default="Insurance Analytics",
        help="Client name for the dashboard header (default: Insurance Analytics).",
    )
    args = ap.parse_args()
    out_path = args.out or os.path.join(args.output_dir, "dashboard.html")
    main(out_path, output_dir=args.output_dir, client_name=args.client_name)
